---
version: "3"

services:
  sgcfg_webapp:
    build:
      context: "./"
      dockerfile: ".docker/Dockerfile.development"
    image: "registry.pmm/sgcfg/webapp:latest"
    restart: always
    # command: php -welsS [::]:8081 -t public
    ports:
      - "8081:8081"
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "app:/app/storage/app/public"
      - "logs:/app/storage/logs"
      - "cache:/app/storage/framework/cache"
      - "sessions:/app/storage/framework/sessions"
      - "views:/app/storage/framework/views"
    # depends_on:
    #   - "sgcfg_database"
    # links:
    #   - "sgcfg_database"
    network_mode: bridge

    env_file:
      - ".env"
    environment:
      docker: "true"
      # DB_CONNECTION: "pgsql"
      # DB_HOST: "sgcfg_database"
      # DB_PORT: "5432"
      # DB_DATABASE: "postgres"
      # DB_USERNAME: "postgres"
      # DB_PASSWORD: "postgres"

    cpu_shares: 128
    mem_reservation: 128m
    mem_limit: 256m
    memswap_limit: -1
    privileged: true
    container_name: "sgcfg_webapp"

  # sgcfg_database:
  #   build:
  #     context: "../"
  #     dockerfile: "database/.docker/Dockerfile.development"
  #   image: "registry.pmm/sgcfg/database:latest"
  #   restart: "always"
  #   volumes:
  #     # - "./initial_data:/docker-entrypoint-initdb.d"
  #     - "dbdata:/var/lib/postgresql/data:rw"
  #   ports:
  #     - "5432:5432"
  #   network_mode: bridge

  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres

  #   cpu_shares: 128
  #   mem_reservation: 128m
  #   mem_limit: 256m
  #   memswap_limit: -1
  #   privileged: true
  #   container_name: sgcfg_database

  # sgcfg_adminer:
  #   image: adminer:4.8.1
  #   restart: always
  #   ports:
  #     - "54320:8080"
  #   # depends_on:
  #   #   - sgcfg_database
  #   links:
  #     - sgcfg_database
  #   network_mode: bridge

  #   environment:
  #     ADMINER_DEFAULT_SERVER: sgcfg_database
  #     ADMINER_DESIGN: pepa-linha-dark
  #     # ADMINER_DESIGN: nette
  #     # ADMINER_DESIGN: mancave
  #     # ADMINER_DESIGN: galkaev
  #     # ADMINER_DESIGN: hydra

  #   cpu_shares: 128
  #   mem_reservation: 128m
  #   mem_limit: 256m
  #   memswap_limit: -1
  #   privileged: true
  #   container_name: sgcfg_adminer

volumes:
  app:
    name: sgcfg_storage_app
  logs:
    name: sgcfg_storage_logs
  cache:
    name: sgcfg_storage_cache
  sessions:
    name: sgcfg_storage_sessions
  views:
    name: sgcfg_storage_views
  # dbdata:
  #   name: sgcfg_database
